### ISSUE TITLE
bug in strengths_dir function

### ISSUE THREAD

**Issue by samyncn** [FIU-Neuro/brainconn#39]
**Describe the bug**
The output does not give in and out strength (is, os), only the total strength(str).

**Expected behavior**
I expect three Nx1 arrays with is, os, and str, but I obtain only one.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04, Browser Chrome - version 69.0.3497.100 

**How to fix**
To fix, change the line 141 with this 
"return istr, ostr, istr + ostr"

**Comment by adamkimbler** [comment]
Thanks for reporting this. It's been correct in #40
